-- CREATE SCHEMA hw

DROP TABLE IF EXISTS hw.DATA607_01_MOVIES;

CREATE TABLE hw.DATA607_01_MOVIES
	(USER_ID INT NULL,
    AGE INT NULL,
	GENDER VARCHAR(10) NULL,
	MOVIE VARCHAR(50) NULL,
	RATING VARCHAR(10) NULL	)

SELECT * FROM hw.DATA607_01_MOVIES;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/movieRatingsScrubbed.csv' 
INTO TABLE hw.DATA607_01_MOVIES
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(USER_ID, @age, @gender, MOVIE, @rating)

SET
AGE = nullif(@age,-1),
GENDER = nullif(@gender,-1),
RATING = nullif(@rating,-1)
;

SELECT COUNT(*) FROM hw.DATA607_01_MOVIES;